const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#22C55E",
    background: "#F4F7F4",
    foreground: "#0a0a0a",
    card: "#FFFFFF",
    cardForeground: "#0a0a0a",
    primary: "#22C55E",
    primaryForeground: "#FFFFFF",
    secondary: "#E8F5E9",
    secondaryForeground: "#1a1a1a",
    muted: "#F0F0F0",
    mutedForeground: "#737373",
    accent: "#16A34A",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E2E8E2",
    input: "#E2E8E2",
    surface: "#FFFFFF",
    surfaceAlt: "#F4F7F4",
    warning: "#F59E0B",
    info: "#3B82F6",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#22C55E",
    background: "#0D0D0D",
    foreground: "#FFFFFF",
    card: "#1A1A1A",
    cardForeground: "#FFFFFF",
    primary: "#22C55E",
    primaryForeground: "#0D0D0D",
    secondary: "#1E2E1E",
    secondaryForeground: "#FFFFFF",
    muted: "#2A2A2A",
    mutedForeground: "#888888",
    accent: "#16A34A",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2A",
    input: "#2A2A2A",
    surface: "#1A1A1A",
    surfaceAlt: "#242424",
    warning: "#F59E0B",
    info: "#3B82F6",
  },
  radius: 12,
};

export default colors;
